

import Footer from "../components/Footer";
import { ReactLenis } from "../utils/Lenis";
import PNav from "../components/ProjectComponents/PNav";
import Banner from "../components/ProjectComponents/Banner";
import Text from "../components/ProjectComponents/Text";
import ProjectDetails from "../components/ProjectComponents/ProjectDetails";
import MovingImg from "../components/ProjectComponents/MovingImg";
import Title from "../components/ProjectComponents/Title";
import Video from "../components/ProjectComponents/Video";
import Divider from "../components/Divider";
import HeadImg from "../components/ProjectComponents/HeadImg";
import STitle from "../components/ProjectComponents/STitle";



export default function project() {
    const tools = ["Unity",
        "Blender",
        'Audacity',
        'HTML CSS JS PHP',
        'Dall-E',
        'Materialize'];
    const P1 = "The 8th Continent is an immersive video game installation that addresses plastic pollution. Players explore a virtual environment inspired by the Great Pacific Garbage Patch, rescuing animals trapped by waste. Each freed animal reveals voice-recorded insights from past participants."
    const P2 = "After all creatures are saved, the environment transforms: colors brighten, a soft piano melody fades in, and players experience a brief, utopian scene. Soon after, trash comes back up, slightly re-polluting the landscape. The message “We still have a lot to clean up!” appears, urging continued action as the game restarts."
    const P3 = "At the end of the game, the players have the option to share their thoughts through a voice recording to be included in the game via a website (server currently inactive)."
    const P4 = "The installation was designed for The Visualization and Emerging Media Studio at UBC Okanagan which is a large, curved extended reality (XR) display, offering a 3D viewing experience with 3D glasses."
    const P5 = "Spanning over 36,501 square inches across 40 screens, the setup allowed multiple viewers to engage with the work simultaneously, immersing them in an expansive digital landscape. "
    const P6 = "The initial version of The 8th Continent featured a snowy forest inspired by British Columbia, but it was later redesigned to represent the Great Pacific Garbage Patch as a frozen “8th Continent.” "
    const P7 = "This arctic island, composed of trash embedded in glaciers, was crafted using 3D and AI-based techniques. The terrain was sculpted in Blender, with a scattered water bottle texture generated by DALL-E and layered with ice effects to create the look of plastic trapped under ice."
    const P75 = "Using Blender, the final texture was baked into a high-resolution diffuse image, and normal and roughness maps were created with Materialize software to enhance realism."
    const P8 = "At the island’s center, a large billboard serves as an in-game interface, displaying instructions and participant quotes, providing a platform for public voices within the immersive environment. By providing spatiality and material permanence to the voice recordings through text, this work offers the public an opportunity to reclaim commercial screens and amplify their voices."
    

    return (
        <ReactLenis root>
            <main className=" bg-grain flex min-h-screen flex-col bg-[#fff] ">

                <PNav />
                <Banner Title={"THE 8TH CONTINENT"} />


                <HeadImg imageSrc={"/T8C/header.webp"} alt={"People interacting with a large screen"} />

                <div className="container m-auto px-6 xl:px-12 py-0 ">


                    <ProjectDetails
                        tools={tools}
                        desc={"A video game installation on plastic pollution with participant-created voice recordings. Developed for Canada’s highest-resolution 3D, VR-ready wall"}
                        year={"2023"}
                        duration={"3-4 months"} />
                    <Divider />
                    <div className="md:py-8" />
                    <div className="grid grid-cols-1 md:grid-cols-2 px-0 py-8 ">
                        <div className=" flex flex-col justify-center items-start col-span-1 px-8  ">
                            <STitle title={"The Narrative"} />
                            <Text text={P1} />
                        </div>

                        <div className="flex items-center col-span-1 p-8 ">
                            <Video fallbackSrc={"/T8C/Doe.mp4"}
                            src={"https://tksoio8smstmaj9d.public.blob.vercel-storage.com/T8C/Doe-HwPRxjPkNcUPOT95kzETMwaBPQNUFU.mp4"}  />
                        </div>
                    </div>
                    <div className="md:py-8" />
                    <div className="grid grid-cols-1 md:grid-cols-2 px-0 py-8 ">
                        <div className=" flex items-center col-span-1  p-8  ">
                            <MovingImg imageSrc={"/T8C/end0.webp"} />
                        </div>

                        <div className="flex items-center col-span-1 px-8 ">
                            <Text text={P2} />
                        </div>
                    </div>
                    <div className="md:py-8" />
                    <MovingImg imageSrc={"/T8C/end1.webp"} />
                    <div className="md:py-8" />

                    <div className="grid grid-cols-1 md:grid-cols-2 px-0 py-8 ">
                        <div className=" flex flex-col justify-center items-start col-span-1 px-8  ">
                            <STitle title={"Participatory Content Creation"} />
                            <Text text={P3} />
                        </div>

                        <div className="flex items-center col-span-1 p-0 md:p-20 ">
                            <MovingImg imageSrc={"/T8C/record.webp"} />
                        </div>
                    </div>

                    <div className="grid grid-cols-1 lg:grid-cols-3 px-0 py-8 ">
                        <div className=" flex flex-col justify-center items-start col-span-1 p-8  ">
                            <Video fallbackSrc={"/T8C/Owl.mp4"} 
                            src={"https://tksoio8smstmaj9d.public.blob.vercel-storage.com/T8C/Owl-pKBPrxcApAKoLbEvbbb1whm8W6H0dT.mp4"}/>
                        </div>

                        <div className="flex items-center col-span-1 lg:col-span-2 p-0 ">
                            <MovingImg imageSrc={"/T8C/ani2.webp"} />
                        </div>
                    </div>

                    <div className="md:py-8" />

                    <div className="grid grid-cols-1 lg:grid-cols-3 px-0 py-8 ">
                        <div className=" flex flex-col justify-center items-start col-span-1 px-8  ">
                            <STitle title={"Canada’s Highest-resolution, 3D, VR-ready Video Wall"} />
                        </div>

                        <div className="flex items-center col-span-1 lg:col-span-2 p-0 ">
                            <MovingImg imageSrc={"/T8C/vems.webp"} />
                        </div>
                    </div>

                    <div className="md:py-8" />



                    <div className="grid grid-cols-1 lg:grid-cols-3 px-0 py-8 ">
                        <div className=" flex flex-col justify-center items-start col-span-1 p-8 order-2 ">
                            <Text text={P4} />
                        </div>

                        <div className="flex items-center col-span-1 lg:col-span-2 p-0 order-1">
                            <MovingImg imageSrc={"/T8C/screen.webp"} />
                        </div>
                    </div>

                    <div className="md:py-8" />

                    <div className="grid grid-cols-1 lg:grid-cols-3 px-0 py-8 ">
                        <div className=" flex flex-col justify-center items-start col-span-1 px-8 pb-8  ">
                            <STitle title={"Shared Immersive XR Experience"} />
                            <Text text={P5} />
                        </div>

                        <div className="flex items-center col-span-1 lg:col-span-2 p-0 ">
                            <MovingImg imageSrc={"/T8C/screen2.webp"} />
                        </div>
                    </div>
                    <div className="md:py-16" />
                    <Video fallbackSrc={"/T8C/Deer.mp4"}
                    src={"https://tksoio8smstmaj9d.public.blob.vercel-storage.com/T8C/Deer-3dbSke1TBNatblACreW8jsPb2AlA8x.mp4"} />
                    <div className="md:py-16" />
                    <div className="grid grid-cols-1 lg:grid-cols-3 px-0 py-8 ">
                        <div className=" flex items-center justify-center col-span-1  px-0 ">
                            <Title title={"Environment Design"} />
                        </div>

                        <div className="flex items-center col-span-1  lg:col-span-2 p-8 ">
                            <MovingImg imageSrc={"/T8C/island.webp"} alt={'a island'} />
                        </div>
                    </div>
                    <div className="md:py-8" />
                    <div className="grid grid-cols-1 lg:grid-cols-3 px-0 py-8 ">
                        <div className=" flex flex-col justify-center items-start col-span-1 px-8 pb-8 order-2 ">
                            <STitle title={"Initial Design"} />
                            <Text text={P6} />
                        </div>

                        <div className="flex items-center col-span-1 lg:col-span-2 p-8 order-1 ">
                            <MovingImg imageSrc={"/T8C/old.webp"} />
                        </div>
                    </div>

                    <div className="md:py-8" />
                    <MovingImg imageSrc={"/T8C/island2.webp"} />
                    <div className="md:py-8" />


                    <div className="grid grid-cols-1 md:grid-cols-2 px-0 py-8 ">
                        <div className=" flex flex-col justify-center items-start col-span-1 px-8 pb-8 ">

                            <Text text={P7} />
                        </div>

                        <div className="flex items-center justify-center col-span-1  p-8  ">
                            <MovingImg imageSrc={"/T8C/bottle.webp"} />
                        </div>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 px-0 py-8 ">
                        <div className=" flex flex-col justify-center items-start col-span-1 px-8 pb-8 order-2">

                            <Text text={P75} />
                        </div>

                        <div className="flex items-center justify-center col-span-1  p-8 order-1 ">
                            <MovingImg imageSrc={"/T8C/ter1.webp"} />
                        </div>
                    </div>

                    <div className="md:py-8" />
                    <MovingImg imageSrc={"/T8C/ter2.webp"} />
                    <div className="md:py-8" />

                    <div className="grid grid-cols-1 md:grid-cols-2 px-0 py-8 ">
                        <div className=" flex flex-col justify-center items-start col-span-1 px-8 pb-8 ">

                            <Text text={P8} />
                        </div>

                        <div className="flex items-center justify-center col-span-1  p-8  ">
                            <Video fallbackSrc={"/T8C/bunny.mp4"}
                            src={"https://tksoio8smstmaj9d.public.blob.vercel-storage.com/T8C/bunny-IhEqOPdd3urH6wOxFcOGth524KKHQy.mp4"}/>
                        </div>
                    </div>
                    <div className=" py-8 md:py-16" />
                    <MovingImg imageSrc={"/T8C/sign.webp"} />
                    <div className=" py-8 md:py-16" />
                    <div className=" flex justify-center">
                    <Title title={"Game Play"} />
                    </div>
                    
                    <div style={{ padding: '56.25% 0 0 0', position: 'relative' }}>
                        <iframe
                            src="https://www.youtube.com/embed/4sPqCH1SCuM?si=4g-r07STP-brs0vL"
                            allow="autoplay; fullscreen; picture-in-picture; clipboard-write"
                            style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%' }}
                            title="The Eighth Continent"
                        ></iframe>
                    </div>
                
                    <div className=" py-8 md:py-16" />
                    <MovingImg imageSrc={"/T8C/ani0.webp"} />
                    <div className=" py-8 md:py-16" />
                    <MovingImg imageSrc={"/T8C/end2.webp"} />
                    <div className=" py-8 md:py-16" />





                </div>
                <Footer />

            </main>
        </ReactLenis>
    );
}

// <MovingImg imageSrc="/Landscape.png" alt="jos" />

/*
 <div className="grid grid-cols-1 md:grid-cols-2 px-0 py-16 order-2">
                        <div className=" flex items-center col-span-1  p-8 ">

                        </div>

                        <div className="flex items-center col-span-1  p-8 order-1">

                        </div>
</div>
                    
<div className="grid grid-cols-1 md:grid-cols-2 px-0 py-16 ">
            <div className="col-span-1 p-4">
              
            </div>

            <div className="col-span-1 p-4">

            </div>

</div>
*/
